version: '2'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bundle exec rails s

  db:
    image: mysql
    environment:
      USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306
    volumes:
       - db:/var/lib/mysql

volumes:
  db:
